# Generated by Django 3.2 on 2021-05-22 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='foodsheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=10)),
                ('catagory', models.CharField(max_length=10)),
                ('food_1', models.CharField(default='', max_length=50)),
                ('food_2', models.CharField(max_length=50)),
                ('food_3', models.CharField(max_length=50)),
                ('food_4', models.CharField(max_length=50)),
                ('food_5', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='User_Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(default='', max_length=50)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('pic_url', models.CharField(max_length=255)),
                ('mtext', models.CharField(blank=True, max_length=255)),
                ('mdt', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
