# Generated by Django 3.2 on 2021-10-31 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodlinebot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=10)),
                ('inout', models.CharField(max_length=5)),
                ('count', models.IntegerField()),
                ('earnper', models.DecimalField(decimal_places=3, max_digits=3)),
                ('note', models.CharField(max_length=100)),
            ],
        ),
    ]
