# Generated by Django 3.2 on 2021-10-31 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodlinebot', '0002_stockrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockrecord',
            name='price',
            field=models.DecimalField(decimal_places=2, default=3, max_digits=3),
            preserve_default=False,
        ),
    ]
