# Generated by Django 3.2 on 2021-10-31 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodlinebot', '0003_stockrecord_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockrecord',
            name='earnper',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
    ]
