# Generated by Django 3.2 on 2021-11-01 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodlinebot', '0005_alter_stockrecord_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockrecord',
            name='earnper',
            field=models.DecimalField(decimal_places=2, max_digits=3, null=True),
        ),
    ]
