# Generated by Django 3.2 on 2021-05-23 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roombot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textfarm',
            name='creator',
            field=models.CharField(max_length=20, verbose_name='作者'),
        ),
    ]
