# Generated by Django 3.2 on 2021-09-07 12:47

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roombot', '0003_textfarm_time_edit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diarywrite1',
            name='photo',
            field=models.ImageField(blank=True, default='photo/rainbow.jpg', null=True, upload_to='photo/'),
        ),
        migrations.AlterField(
            model_name='diarywrite1',
            name='title',
            field=models.CharField(max_length=100, verbose_name='標題'),
        ),
        migrations.AlterField(
            model_name='textfarm',
            name='body',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='Type in ..', verbose_name='內容'),
        ),
    ]
