# Generated by Django 3.2 on 2021-09-28 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roombot', '0005_textfarm_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textfarm',
            name='tag',
            field=models.CharField(blank=True, max_length=10, verbose_name='標籤'),
        ),
    ]
