# Generated by Django 3.2 on 2021-10-04 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roombot', '0006_alter_textfarm_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textfarm',
            name='tag',
            field=models.CharField(blank=True, default='Others', max_length=10, verbose_name='標籤'),
        ),
    ]
