# Generated by Django 3.2.7 on 2021-10-24 05:24

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roombot', '0007_alter_textfarm_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='testfarm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('body', ckeditor_uploader.fields.RichTextUploadingField(default='Type in ..', verbose_name='內容')),
            ],
        ),
    ]
